export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCES = "GET_PRODUCTS_SUCCES";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS_DATAILS_REQUEST = "GET_PRODUCTS_DATAILS_REQUEST";
export const GET_PRODUCTS_DATAILS_SUCCES = "GET_PRODUCTS_DATAILS_SUCCES";
export const GET_PRODUCTS_DATAILS_FAIL = "GET_PRODUCTS_DATAILS_FAIL";
export const GET_PRODUCTS_DATAILS_RESET = "GET_PRODUCTS_DATAILS_RESET";